# <div align="center" style="color: #ff5733;">All Query related to Brand</div>

In [1]:
# %% [markdown]
# # Jupyter Notebook Loading Header
#
# This is a custom loading header for Jupyter Notebooks in Visual Studio Code.
# It includes common imports and settings to get you started quickly.

# %% [markdown]
## Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.cloud import bigquery
import os
path = r'C:\Users\DwaipayanChakroborti\AppData\Roaming\gcloud\legacy_credentials\dchakroborti@tonikbank.com\adc.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = path
client = bigquery.Client(project='prj-prod-dataplatform')

# %% [markdown]
## Configure Settings
# Set options or configurations as needed
# Example: pd.set_option('display.max_columns', None)

In [2]:
sq = """WITH 
W_VAS_FEES
AS
(
  select loanId, sum(scheduleChargeAmount) as VasFees  from prj-prod-dataplatform.dl_loans_db_raw.tdbk_loan_repayment_schedule  f
  group by 1
),
W_PROMOTERS
AS
(
  SELECT DISTINCT a.digitalLoanAccountId, a.promoterId, 
  #a.promoterName,
  b.firstName || Case when b.middleName is not null then ' ' || b.middleName End  || Case when b.lastName is not null then ' ' || b.lastName End as promoterName,
  CASE WHEN C.Date_of_leaving = DATE '3000-01-01' THEN NULL ELSE C.Date_of_leaving END AS Promoter_LWD, 
  row_number() over(partition by a.digitalLoanAccountId order by a.id desc) as rnk  
  FROM
  prj-prod-dataplatform.dl_loans_db_raw.tdbk_qr_promoter_details a
  left join prj-prod-dataplatform.dl_dynamo_db_raw.tdbk_promotors_user_dtl  b
  on a.promoterId = b.id
  LEFT JOIN prj-prod-dataplatform.dap_ds_poweruser_playground.SIL_Promoters_DOJ C
  ON TRIM(C.Promoter_ID) = TRIM(b.id)
  WHERE
  a.promoterId IS NOT NULL
)
,
W_LOAN_MASTER_a as
(
    SELECT a.digitalLoanAccountId, a.startApplyDateTime, a.purposeDescription,
    CASE 
    WHEN a.cddInitiatedDateAndTime IS NOT NULL AND a.cddVerificationDateAndTime IS NOT NULL THEN a.cddVerificationDateAndTime
    WHEN a.cddInitiatedDateAndTime IS NULL AND COALESCE(a.rejectedDateTime,a.approvedDateTime,a.Stage1_DateTime) IS NOT NULL THEN COALESCE(a.rejectedDateTime,a.approvedDateTime,a.Stage1_DateTime)
    ELSE NULL END AS decision_date, 
    a.disbursementDateTime, a.purpleKey, a.merchantName,
    d.BrandStores,
    a.stage1status, a.approvedLoanAmount, a.downPaymentAmount,
    (coalesce(cast(c.price as float64),0)) as Items_Sold_Price,
    a.isTermsAndConditionsAccepted, 
    CASE 
    WHEN a.cddInitiatedDateAndTime IS NOT NULL AND a.cddVerificationDateAndTime IS NOT NULL THEN a.flagApproval
    WHEN a.cddInitiatedDateAndTime IS NULL AND COALESCE(a.rejectedDateTime,a.approvedDateTime,a.Stage1_DateTime) IS NOT NULL AND a.stage1status in ('EXPIRED','APPROVED') THEN 1 
    ELSE 0 END AS flagApproval, 
    CASE 
    WHEN a.cddInitiatedDateAndTime IS NOT NULL AND a.cddVerificationDateAndTime IS NOT NULL THEN flagRejection
    WHEN a.cddInitiatedDateAndTime IS NULL AND COALESCE(a.rejectedDateTime,a.approvedDateTime,a.Stage1_DateTime) IS NOT NULL AND COALESCE(a.stage1status,'XNA') NOT in ('EXPIRED','APPROVED') THEN 1 
    ELSE 0 END AS flagRejection, 
    a.flagDisbursement, a.disbursedLoanTenur, a.disbursedLoanAmount, a.BNPL_PRODUCT_CATEGORY_CNT, a.employmentstatus, a.new_loan_type,
    B.promoterId, 
    coalesce(initcap(b.promoterName) ,'XNA') as Promoter,
    b.Promoter_LWD as Promoter_LWD,
    d.TSM, d.DateOpened,
    case when e.vas_flag = 'true' then 1 else 0 end as VasFlag,
    #f.scheduleChargeAmount as VasFees
    f.VasFees,
    FROM 
    prj-prod-dataplatform.risk_credit_mis.loan_master_table a
    left join W_PROMOTERS b
    on a.digitalLoanAccountId = b.digitalLoanAccountId and b.rnk = 1
    left join prj-prod-dataplatform.dl_loans_db_raw.tdbk_bnpl_trans_category c 
    on a.digitalLoanAccountId = c.digitalLoanAccountId
    left join prj-prod-dataplatform.dap_ds_poweruser_playground.POS_TSM_MAPIING d
    on d.purpleKey = a.purpleKey
    left join prj-prod-dataplatform.dl_loans_db_raw.tdbk_digital_loan_application e
    on e.loanAccountNumber = a.loanAccountNumber
    left join W_VAS_FEES  f
    on a.loanAccountNumber = f.loanId# and f.repaymentNumber = 1
    WHERE
    a.new_loan_type = 'SIL-Instore'
    AND
    DATE_TRUNC(a.startApplyDateTime,DAY) BETWEEN DATE '2022-03-26' AND (CURRENT_DATE - 1)
  )
, W_LOAN_MASTER
AS
(
  SELECT digitalLoanAccountId, startApplyDateTime, DECISION_DATE, disbursementDateTime, purpleKey, BrandStores, merchantName, purposeDescription as Commodity, 
  case when stage1status in ('EXPIRED','APPROVED') then approvedLoanAmount end as approvedLoanAmount,
  case when stage1status in ('EXPIRED','APPROVED') then CAST(downPaymentAmount AS FLOAT64) end as downPaymentAmount,
  #approvedLoanAmount, 
  COALESCE(isTermsAndConditionsAccepted,0) AS APP_COMPLETED, 
  flagApproval,
  CASE WHEN DECISION_DATE IS NOT NULL AND flagApproval =1 AND flagDisbursement = 0 AND stage1status in ('APPROVED') THEN 1 ELSE 0 END AS APPLICATION_APPROVED_NOT_BOOKED_CNT,
  CASE WHEN DECISION_DATE IS NOT NULL AND flagApproval =1 AND flagDisbursement = 0 AND stage1status in ('EXPIRED') THEN 1 ELSE 0 END AS APPLICATION_EXPIRED,
  flagRejection,
  flagDisbursement, disbursedLoanTenur, disbursedLoanAmount, 
  CASE WHEN COALESCE(BNPL_PRODUCT_CATEGORY_CNT,0) > 1 THEN 'Y' Else 'N' END AS BUNDLED,
  Initcap(employmentstatus) AS employmentstatus, promoterId, Promoter, Promoter_LWD, 
  TSM, DateOpened,
  sum(case when stage1status in ('EXPIRED','APPROVED') then Items_Sold_Price end) as Items_Sold_Price,
  max(VasFlag) as VasFlag ,
  max(VasFees) as VasFees  from W_LOAN_MASTER_a
    WHERE
  new_loan_type = 'SIL-Instore'
  #loanType = 'BNPL' AND purpleKey is not null and (isUserAtStore = 1 or isUserAtStore is null)
  AND
  DATE_TRUNC(startApplyDateTime,DAY) BETWEEN DATE '2022-03-26' AND (CURRENT_DATE - 1)
  Group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24, 25
)
,
W_DTS
AS
(
    SELECT DISTINCT DATE_TRUNC(startApplyDateTime,MONTH) AS MONTH, DATE_TRUNC(startApplyDateTime,DAY) dt,
    case when DATE_TRUNC(startApplyDateTime,DAY) between '2024-02-09' and '2024-03-09' then 'B'
         when DATE_TRUNC(startApplyDateTime,DAY) > '2024-03-09' then 'A'
         when DATE_TRUNC(startApplyDateTime,DAY) < '2024-02-09' then 'C' end date_flag
    FROM prj-prod-dataplatform.risk_credit_mis.loan_master_table 
    WHERE
    DATE_TRUNC(startApplyDateTime,DAY) BETWEEN DATE '2022-03-26' AND (CURRENT_DATE - 1)
)
,
delq_base as
(select lmt.loanAccountNumber, lmt.digitalLoanAccountId,
sum(case when ldd.min_inst_def30 = 1 then 1 else 0 end) fpd30_cnt,
sum(case when ldd.obs_min_inst_def30 >= 1 then 1 else 0 end) obs_fpd30_cnt,
sum(case when ldd.min_inst_def30 = 1 then lmt.disbursedloanamount else 0 end) fpd30_v,
sum(case when ldd.obs_min_inst_def30 >= 1 then lmt.disbursedloanamount else 0 end) obs_FPD30_v,
sum(case when ldd.min_inst_def30 = 2 then 1 else 0 end) spd30_cnt,
sum(case when ldd.obs_min_inst_def30 >= 2 then 1 else 0 end) obs_spd30_cnt,
sum(case when ldd.min_inst_def30 = 2 then lmt.Total_Outstanding_Principal else 0 end) spd30_v,
sum(case when ldd.obs_min_inst_def30 >= 2 then lmt.disbursedloanamount else 0 end) obs_spd30_v,
sum(case when ldd.min_inst_def30 = 3 then 1 else 0 end) tpd30_cnt,
sum(case when ldd.obs_min_inst_def30 >= 3 then 1 else 0 end) obs_tpd30_cnt,
sum(case when ldd.min_inst_def30 = 3 then lmt.Total_Outstanding_Principal else 0 end) tpd30_v,
sum(case when ldd.obs_min_inst_def30 >=3 then lmt.disbursedloanamount else 0 end) obs_tpd30_v,
sum(case when ldd.obs_min_inst_def30 >= 3 and ldd.min_inst_def30 in (1,2,3) then 1 else 0 end) fstpd30_cnt,
sum(Case when ldd.obs_min_inst_def30 >= 3 then 1 else 0 end) obs_fstpd30_cnt
from
`risk_credit_mis.loan_master_table` lmt
left join `prj-prod-dataplatform.risk_credit_mis.loan_deliquency_data` ldd on ldd.loanAccountNumber = lmt.loanAccountNumber
where lmt.flagDisbursement = 1
group by 1,2
),
loanbase as 
(select a.digitalLoanAccountId, a.startApplyDateTime, 
a.DECISION_DATE,
a.disbursementDateTime,
a.purpleKey,
case when a.purpleKey in ('MV5BS04', 'MD1R4BJ', 'M6EKLNI', 'MYXLHQ4', 'MHZDIVT', 'M2JQP9L', 'MYRK3EJ', 'M7SE4LZ', 'MDGYHQJ', 'MQTA03J', 'M7261RR', 'MR0G4XP', 'M8A59CP', 'M7ZLTH1', 'MWG98DQ', 'MA296F1') then 'RBP Pilot' else 'Other' end RBP_Flag,
a.merchantName,
a.BrandStores,
a.approvedLoanAmount,
a.downPaymentAmount,
a.APP_COMPLETED,
a.flagApproval,
a.APPLICATION_APPROVED_NOT_BOOKED_CNT,
a.APPLICATION_EXPIRED,
a.flagRejection,
a.flagDisbursement,
a.disbursedLoanTenur,
a.disbursedLoanAmount,
a.BUNDLED,
a.employmentstatus,
a.promoterId,
a.TSM,
a.DateOpened,
a.Items_Sold_Price,
a.VasFlag,
a.VasFees,
db.loanAccountNumber,
db.fpd30_cnt,
db.obs_fpd30_cnt,
db.fpd30_v,
db.obs_FPD30_v,
db.spd30_cnt,
db.obs_spd30_cnt,
db.spd30_v,
db.obs_spd30_v,
db.tpd30_cnt,
db.obs_tpd30_cnt,
db.tpd30_v,
db.obs_tpd30_v,
db.fstpd30_cnt,
db.obs_fstpd30_cnt
from W_LOAN_MASTER a
left join delq_base db on db.digitalLoanAccountId = a.digitalLoanAccountId
) -- No duplicate digitalLoanAccountId in loanbase table
,
W_MERCHANTS
AS
(
    SELECT DISTINCT purpleKey AS MERCHANT_CODE, merchantName as Store, 
    BrandStores Merchant,
    CASE WHEN purplekey IN ('M9ZK6IU','MV4UO0X','M2G78K4','MEKA38B','MOE3JQH') THEN 'N' ELSE 'Y' END AS ACTIVE,
    COALESCE(TSM,'XNA') AS TSM, DateOpened, 
    BUNDLED, employmentstatus, promoterId
    FROM loanbase
),
W_STARTED
AS
(
    SELECT date(format_date('%Y-%m-%d',DATE_TRUNC(startApplyDateTime,MONTH))) AS APP_START_DATE,
    DATE_TRUNC(startApplyDateTime,DAY) dt,
    case when DATE_TRUNC(startApplyDateTime,DAY) between '2024-02-09' and '2024-03-09' then 'B'
         when DATE_TRUNC(startApplyDateTime,DAY) > '2024-03-09' then 'A'
         when DATE_TRUNC(startApplyDateTime,DAY) < '2024-02-09' then 'C' end date_flag,
    purpleKey, employmentstatus
    , max(merchantName) merchantName
    , max(RBP_Flag) RBP_Flag 
    ,COUNT(DISTINCT BrandStores) Merchant,
    min(DateOpened) pos_startofoperation,
    count(distinct  TSM) TSM,
    count(distinct promoterId) Promoters,
    COUNT(1) AS APP_STARTED, SUM(APP_COMPLETED) AS APP_COMPLETED, 
    #SUM(CASE WHEN DECISION_DATE IS NOT NULL AND flagApproval =1 AND flagDisbursement = 0 THEN 1 ELSE 0 END) AS APPLICATION_APPROVED_NOT_BOOKED_CNT,
    SUM(APPLICATION_APPROVED_NOT_BOOKED_CNT) AS APPLICATION_APPROVED_NOT_BOOKED_CNT,
    SUM(APPLICATION_EXPIRED) AS APPLICATION_EXPIRED,
    SUM(CASE WHEN DECISION_DATE IS NOT NULL AND flagApproval =1 AND flagDisbursement = 0 THEN approvedLoanAmount ELSE 0 END) AS APPROVED_NOT_BOOKED_VOLUME
    FROM loanbase
    WHERE startApplyDateTime IS NOT NULL
    GROUP BY 1,2,3,4,5
)
,
W_DECIDED
AS
(
    SELECT 
    date(format_date('%Y-%m-%d',DATE_TRUNC(DECISION_DATE,MONTH))) AS APP_DECISION_DATE,
    DATE_TRUNC(DECISION_DATE,DAY) dt,
    case when DATE_TRUNC(DECISION_DATE,DAY) between '2024-02-09' and '2024-03-09' then 'B'
         when DATE_TRUNC(DECISION_DATE,DAY) > '2024-03-09' then 'A'
         when DATE_TRUNC(DECISION_DATE,DAY) < '2024-02-09' then 'C' end date_flag
    , purpleKey, employmentstatus
    , max(merchantName) merchantName
    ,max(RBP_Flag) RBP_Flag,
    COUNT(DISTINCT BrandStores) Merchant,
    min(DateOpened) pos_startofoperation,
    count(distinct  TSM) TSM,
    count(distinct promoterId) Promoters,
    COUNT(1) AS APP_DECIDED, SUM(flagApproval) AS APP_APPROVED, SUM(flagRejection) AS APP_REJECTED, 
    SUM(approvedLoanAmount) AS approvedLoanAmount, SUM(downPaymentAmount) AS downPaymentAmount, SUM(Items_Sold_Price) AS Items_Sold_Price
    FROM loanbase
    WHERE DECISION_DATE IS NOT NULL
    GROUP BY 1,2,3,4,5
)
,
W_BOOKED
AS
(
    SELECT 
    date(format_date('%Y-%m-%d',DATE_TRUNC(disbursementDateTime,MONTH))) AS APP_BOOKED_DATE,
    DATE_TRUNC(disbursementDateTime,DAY) dt,
    case when DATE_TRUNC(disbursementDateTime,DAY) between '2024-02-09' and '2024-03-09' then 'B'
         when DATE_TRUNC(disbursementDateTime,DAY) > '2024-03-09' then 'A'
         when DATE_TRUNC(disbursementDateTime,DAY) < '2024-02-09' then 'C' end date_flag
    , purpleKey
    , employmentstatus
    , max(merchantName) merchantName
    , max(RBP_Flag) RBP_Flag
    ,COUNT(DISTINCT BrandStores) Merchant,
    count(distinct  TSM) TSM,
    count(distinct promoterId) Promoters,
    SUM(flagDisbursement) AS APP_BOOKED, SUM(disbursedLoanAmount) AS APP_BOOKED_VOLUME, 
    SUM(disbursedLoanTenur) AS APP_BOOKED_TENURE, 
    SUM(CASE WHEN disbursedLoanTenur > 3 THEN 1 ELSE 0 END) AS VAS_ELIGIBLE_BASE,
    SUM(VasFlag) AS VAS_SOLD, SUM(VasFees) AS VAS_SOLD_VOLUME,
    SUM(fpd30_cnt) fpd30_cnt,
    SUM(obs_fpd30_cnt) obs_fpd30_cnt,
    SUM(fpd30_v) fpd30_v,
    SUM(obs_FPD30_v) obs_FPD30_v,
    SUM(spd30_cnt) spd30_cnt,
    sum(obs_spd30_cnt) obs_spd30_cnt,
    SUM(spd30_v) spd30_v,
    SUM(obs_spd30_v) obs_spd30_v,
    SUM(tpd30_cnt) tpd30_cnt,
    SUM(obs_tpd30_cnt)obs_tpd30_cnt,
    SUM(tpd30_v) tpd30_v,
    SUM(obs_tpd30_v) obs_tpd30_v,
    SUM(fstpd30_cnt) fstpd30_cnt,
    SUM(obs_fstpd30_cnt) obs_fstpd30_cnt
    FROM loanbase
    WHERE disbursementDateTime IS NOT NULL
    GROUP BY 1,2,3,4,5
)
select coalesce(upper(tbtc.brandName), 'NA') brandName
,date(format_date('%Y-%m-%d', lmt.disbursementDateTime)) Booking_Date
, RBP_Flag, new_loan_type
, count(lmt.digitalLoanAccountId) cnt
, sum(lmt.disbursedLoanAmount) disbursedamount
, SUM(loanbase.disbursedLoanTenur) AS APP_BOOKED_TENURE, 
    SUM(CASE WHEN loanbase.disbursedLoanTenur > 3 THEN 1 ELSE 0 END) AS VAS_ELIGIBLE_BASE,
    SUM(loanbase.VasFlag) AS VAS_SOLD, SUM(loanbase.VasFees) AS VAS_SOLD_VOLUME,
    SUM(loanbase.fpd30_cnt) fpd30_cnt,
    SUM(loanbase.obs_fpd30_cnt) obs_fpd30_cnt,
    SUM(loanbase.fpd30_v) fpd30_v,
    SUM(loanbase.obs_FPD30_v) obs_FPD30_v,
    SUM(loanbase.spd30_cnt) spd30_cnt,
    sum(loanbase.obs_spd30_cnt) obs_spd30_cnt,
    SUM(loanbase.spd30_v) spd30_v,
    SUM(loanbase.obs_spd30_v) obs_spd30_v,
    SUM(loanbase.tpd30_cnt) tpd30_cnt,
    SUM(loanbase.obs_tpd30_cnt)obs_tpd30_cnt,
    SUM(loanbase.tpd30_v) tpd30_v,
    SUM(loanbase.obs_tpd30_v) obs_tpd30_v,
    SUM(loanbase.fstpd30_cnt) fstpd30_cnt,
    SUM(loanbase.obs_fstpd30_cnt) obs_fstpd30_cnt
from `risk_credit_mis.loan_master_table` lmt
left join prj-prod-dataplatform.dl_loans_db_raw.tdbk_bnpl_trans_category tbtc on tbtc.digitalLoanAccountId = lmt.digitalLoanAccountId
Left join loanbase on loanbase.digitalLoanAccountId = lmt.digitalLoanAccountId
where new_loan_type like 'SIL-Instore' 
and lmt.flagDisbursement = 1
group by 1,2 ,3,4
order by 2 desc"""

In [3]:
dfbrand = client.query(sq).to_dataframe(progress_bar_type='tqdm')

Job ID 9f3f67a2-edc9-4bed-b57e-2a7bf7f680ac successfully executed: 100%|██████████|
Downloading: 100%|██████████|

In [4]:
print(f"The shape of dfbrand dataframe is: {dfbrand.shape}")

The shape of dfbrand dataframe is: (20461, 24)